# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Identity Server Documentation
site_description: Documentation for WSO2 Identity Server
site_author: WSO2
site_url: https://wso2.com/identity-and-access-management/

# Repository
repo_name: wso2/docs-is
repo_url: https://github.com/wso2/docs-is
edit_uri: https://github.com/wso2/docs-is/edit/master/en/docs/

# Copyright
copyright: WSO2 Identity Server - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'
  
# Navigation
nav:
  - 'Home': index.md
  - 'Quick Start':
    - 'Overview': get-started/overview.md
    - 'Mobile':
      - 'Android': get-started/android.md
      - 'iOS': get-started/ios.md
    - 'Frontend':
      - 'Angular': get-started/angular.md
      - 'React': get-started/react.md
    - 'Backend':
      - 'Java': get-started/java.md
      - 'NodeJs': get-started/nodejs.md
  - 'Guides':
    - 'Get Started': guides/before-you-start.md
    - 'Authentication':
      - 'Web Application': sso/sso-for-traditional-web-app.md
    - 'Multifactor Authentication':
      - guides/mfa.md
    - 'Adaptive Authentication':
      - guides/adaptive.md
    - 'Federation':
      - guides/federation.md
  - 'APIs':
    - 'Overview': develop/rest-apis.md
  - 'Deploy':
    - 'Deploy': deploy/deploying-wso2-identity-server.md
    - 'choose your model': deploy/deploying-wso2-identity-server/choose-your-model.md
  - 'Concepts':
    - concepts/overview.md
  - 'Samples':
    - samples/overview.md
    - 'Android': samples/android.md
  - 'Authentication':
    - 'OAuth Grant Types': guides/oauth-grant-types.md
    - 'Connect an OAuth/OpenID Connect Application': guides/configuring-sso-oidc.md
    - 'OAuth2/ OpenID Connect Configurations': guides/oauth-oidc-configurations.md
    - 'Configure Client Application': guides/configure-client-app.md
    - 'Manage User Sessions': guides/manage-user-sessions.md
    - 'OpenID Connect Logout': guides/sso-oidc-logout.md
  - '': page-not-found.md  
  

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
    
# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 5.9.0
